### ISSUE TITLE
录制斗鱼出错

### ISSUE THREAD

**Issue by 7rikka** [nICEnnnnnnnLee/BilibiliLiveRecorder#10]
已加cookies
`C:\Users\x\Downloads\Compressed\BilibiliLiveRecord.v2.0>java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=douyu"
douyu 直播录制 version v2.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
70002
发现cookie配置
发送GET请求出现异常！java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.douyu.com/lapi/live/getH5Play/70002
org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
        at org.json.JSONObject.<init>(JSONObject.java:222)
        at org.json.JSONObject.<init>(JSONObject.java:406)
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getLiveObj(RoomDealerDouyu.java:162)
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:109)
        at nicelee.bilibili.Main.main(Main.java:131)
java.lang.NullPointerException
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:110)
        at nicelee.bilibili.Main.main(Main.java:131)
解析失败！！
Exception in thread "main" java.lang.NullPointerException
        at nicelee.bilibili.Main.main(Main.java:137)`

**Comment by 7rikka** [comment]
试了几个别的直播间都正常，就这个有问题
