### ISSUE TITLE
斗鱼不能录制

### ISSUE THREAD

**Issue by ASFLY61** [nICEnnnnnnnLee/BilibiliLiveRecorder#122]
系统：windows11 23H2
工具版本：version v2.26.0
java版本：
java 19.0.1 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
运行报错如下，输入未开播的斗鱼房间号可以正常输入信息，输入开播的房间号就提示这个错误，是java版本的问题吗
java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=flase&liver=douyu"
douyu 直播录制 version v2.26.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
8825216
发现cookie配置
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null
        at nicelee.bilibili.util.JSEngine.run(JSEngine.java:48)
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getLiveObj(RoomDealerDouyu.java:152)
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:109)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:153)
        at nicelee.bilibili.Main.main(Main.java:86)
org.json.JSONException: JSONObject["data"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:770)
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:110)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:153)
        at nicelee.bilibili.Main.main(Main.java:86)
解析失败！！

**Comment by nICEnnnnnnnLee** [comment]
从JDK15开始删除了默认的JS引擎实现，只保留了接口。    

在新版本发布前请使用CI编译的artifacts。-->[传送门](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/actions/runs/6845356327)
