### ISSUE TITLE
感谢大佬修复虎牙，今天突然房间都搜不到了

### ISSUE THREAD

**Issue by ucxl** [nICEnnnnnnnLee/BilibiliLiveRecorder#134]
java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.group(Matcher.java:645)
        at nicelee.bilibili.live.impl.RoomDealerHuya.getRoomInfo(RoomDealerHuya.java:49)
        at nicelee.bilibili.Main.main(Main.java:90)
解析失败！！

**Comment by nICEnnnnnnnLee** [comment]
log要抓全，房间id也未提供。  

盲猜直播是搞活动的直播间，网页结构和普通不同。  

请尝试使用`liver=huya2`。

**Comment by ucxl** [comment]
不好意思，现在发全的来，huya2也不行

D:\desktop\BilibiliLiveRecord.v2.28.0>cd /d D:\desktop\BilibiliLiveRecord.v2.28.0\

D:\desktop\BilibiliLiveRecord.v2.28.0>java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=huya"
huya 直播录制 version v2.28.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
30080238
发送GET请求出现异常！java.io.IOException: Server returned HTTP response code: 403 for URL: http://175.4.52.243/al.flv.huya.com/src/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?t=2&t=2&wsSecret=481ac8ed005844deb5a5bb1770c3ea3d&sdkPcdn=1_1&u=1463041669971&sphdDC=&exsphd=&sphd=&wsTime=66c5e657&seqid=3187503261343&ver=1&sdk_sid=1724245591372&dMod=mseh-32&sv=2408161057&fs=bgct&ctype=huya_adr&sphdcdn=&ali_dispatch_cold_stream=on&ali_redirect_ex_hot=66666001&ali_stream_type=01&ali_stream_type_ring=&ali_orig_station=cn4300&ali_302c=700&ali_st=cn6885&ali_ts=1724245592
当前Room信息:
        shortId - 30080238
        roomId  - 30080238
        userId  - 30080238
                liveStatus      - 0
                description     - [李云龙] 劳资的意太利炮呢！
当前没有在直播

D:\desktop\BilibiliLiveRecord.v2.28.0>pause
请按任意键继续. . .


D:\desktop\BilibiliLiveRecord.v2.28.0>java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=huya2"
huya2 直播录制 version v2.28.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
30080238
当前Room信息:
        shortId - 30080238
        roomId  - 30080238
        userId  - 30080238
        userName        - 回去拿马卡报
        liveStatus      - 1
        title   - [李云龙] 劳资的意太利炮呢！
        description     - [李云龙] 劳资的意太利炮呢！
可提供直播质量:
        0 : 蓝光4M
        2000 : 超清
        500 : 流畅
请输入清晰度代号(:之前的内容，不含空格)
0
开始录制，输入stop停止录制
文件大小: [150] 字节.
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=acda1c18d0e57536e51ba8f6f91853c6&wsTime=66c5e5c1&seqid=3187519374896&ctype=huya_adr&ver=1&fs=bgct&t=2&sphdcdn=&sphdDC=&sphd=&exsphd=&t=2&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463057933110&sdk_sid=1724245441786
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at nicelee.bilibili.util.HttpRequestUtil.download(HttpRequestUtil.java:200)
        at nicelee.bilibili.live.impl.RoomDealerHuyaWup.startRecord(RoomDealerHuyaWup.java:126)
        at nicelee.bilibili.threads.ThRecord.record(ThRecord.java:139)
        at nicelee.bilibili.threads.ThRecord.run(ThRecord.java:50)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=acda1c18d0e57536e51ba8f6f91853c6&wsTime=66c5e5c1&seqid=3187519374896&ctype=huya_adr&ver=1&fs=bgct&t=2&sphdcdn=&sphdDC=&sphd=&exsphd=&t=2&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463057933110&sdk_sid=1724245441786
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3137)
        at nicelee.bilibili.util.HttpRequestUtil.download(HttpRequestUtil.java:187)
        ... 3 more
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
发送GET请求出现异常！java.io.IOException: Server returned HTTP response code: 403 for URL: http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=acda1c18d0e57536e51ba8f6f91853c6&wsTime=66c5e5c1&seqid=3187519374896&ctype=huya_adr&ver=1&fs=bgct&t=2&sphdcdn=&sphdDC=&sphd=&exsphd=&t=2&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463057933110&sdk_sid=1724245441786
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=acda1c18d0e57536e51ba8f6f91853c6&wsTime=66c5e5c1&seqid=3187519374896&ctype=huya_adr&ver=1&fs=bgct&t=2&sphdcdn=&sphdDC=&sphd=&exsphd=&t=2&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463057933110&sdk_sid=1724245441786
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at nicelee.bilibili.util.HttpRequestUtil.download(HttpRequestUtil.java:200)
        at nicelee.bilibili.live.impl.RoomDealerHuyaWup.startRecord(RoomDealerHuyaWup.java:126)
        at nicelee.bilibili.threads.ThRecord.record(ThRecord.java:139)
        at nicelee.bilibili.threads.ThRecord.run(ThRecord.java:50)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=acda1c18d0e57536e51ba8f6f91853c6&wsTime=66c5e5c1&seqid=3187519374896&ctype=huya_adr&ver=1&fs=bgct&t=2&sphdcdn=&sphdDC=&sphd=&exsphd=&t=2&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463057933110&sdk_sid=1724245441786
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3137)
        at nicelee.bilibili.util.HttpRequestUtil.download(HttpRequestUtil.java:187)
        ... 3 more
连接异常，1.0min后重新尝试录制
正在处理，请稍等
正在处理，请稍等
正在处理，请稍等
正在处理，请稍等

**Comment by nICEnnnnnnnLee** [comment]
程序不要断掉，等一分钟后继续

**Comment by ucxl** [comment]
也是不行

连接异常，1.0min后重新尝试录制
正在处理，请稍等
正在处理，请稍等
正在处理，请稍等
正在处理，请稍等
正在处理，请稍等
正在处理，请稍等
文件大小: null 字节.
下载完毕...
下载停止
处理文件中
校对时间戳开始...
校对时间戳完毕。
校对时间戳开始...
校对时间戳完毕。
SignalHandler is running

D:\desktop\BilibiliLiveRecord.v2.28.0>pause
请按任意键继续. . .

**Comment by nICEnnnnnnnLee** [comment]
你设置环境变量`huya.platform=ios`试一试，不成的话短时间内不成了

**Comment by nICEnnnnnnnLee** [comment]
Linux
```
export huya.platform=ios
```
Windows
```
set huya.platform=ios
```

**Comment by ucxl** [comment]
也是不行，不急，大佬有空再看，打扰了

**Comment by nICEnnnnnnnLee** [comment]
说错了，不是设置环境变量，是传参数`-Dhuya.platform=ios`

```
java -Dfile.encoding=utf-8 -jar -Dhuya.platform=ios BiliLiveRecorder.jar "debug=true&check=false&liver=huya2"
```

**Comment by ucxl** [comment]
还是不行的

D:\desktop\BilibiliLiveRecord.v2.28.0>cd /d D:\desktop\BilibiliLiveRecord.v2.28.0\

D:\desktop\BilibiliLiveRecord.v2.28.0>java -Dfile.encoding=utf-8 -jar -Dhuya.platform=ios BiliLiveRecorder.jar "debug=true&check=false&liver=huya2"
huya2 直播录制 version v2.28.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
30080238
当前Room信息:
        shortId - 30080238
        roomId  - 30080238
        userId  - 30080238
        userName        - 回去拿马卡报
        liveStatus      - 1
        title   - [李云龙] 劳资的意太利炮呢！
        description     - [李云龙] 劳资的意太利炮呢！
可提供直播质量:
        0 : 蓝光4M
        2000 : 超清
        500 : 流畅
请输入清晰度代号(:之前的内容，不含空格)
0
RoomDealerHuya-genFlvAntiCode/238 : huya_webh5
RoomDealerHuya-genFlvAntiCode/239 : huya_ios
RoomDealerHuyaWup-getLiveUrl/106 : wsSecret=14d99ef5c21ddde62b3321096714b6a7&wsTime=66c5f2f5&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctype=huya_webh5&fs=bgct
RoomDealerHuyaWup-getLiveUrl/107 : wsSecret=b4ea8fb72098fdc890bd070a7f909507&wsTime=66c5f1c8&seqid=3187617443109&ctype=huya_ios&ver=1&fs=bgct&t=3&sphdcdn=&sphdDC=&sphd=&exsphd=&t=3&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463152922410&sdk_sid=1724248520699
RoomDealerHuyaWup-getLiveUrl/114 : http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=b4ea8fb72098fdc890bd070a7f909507&wsTime=66c5f1c8&seqid=3187617443109&ctype=huya_ios&ver=1&fs=bgct&t=3&sphdcdn=&sphdDC=&sphd=&exsphd=&t=3&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463152922410&sdk_sid=1724248520699
ThRecord-run/44 : http://hw.flv.huya.com/huyalive/1239543153972-1239543153972-11135015062081634304-2479086431400-10057-A-0-1.flv?wsSecret=b4ea8fb72098fdc890bd070a7f909507&wsTime=66c5f1c8&seqid=3187617443109&ctype=huya_ios&ver=1&fs=bgct&t=3&sphdcdn=&sphdDC=&sphd=&exsphd=&t=3&sv=2408161057&dMod=mseh-32&sdkPcdn=1_1&u=1463152922410&sdk_sid=1724248520699
开始录制，输入stop停止录制
文件大小: null 字节.
下载完毕...
下载停止
处理文件中
SignalHandler is running

D:\desktop\BilibiliLiveRecord.v2.28.0>pause
请按任意键继续. . .

**Comment by usedssl** [comment]
<img width="585" height="217" alt="Image" src="https://github.com/user-attachments/assets/f5270056-9416-45a1-91ea-612e5a276108" />获取不到conn的Content-Length怎么办
