### ISSUE TITLE
ubuntu运行不了

### ISSUE THREAD

**Issue by maowayne123** [nICEnnnnnnnLee/BilibiliLiveRecorder#35]
提示找不到合适的播放器：XXXhuya 或者douya之类的

**Comment by maowayne123** [comment]
java.lang.NullPointerException
	at nicelee.bilibili.live.RoomDealer.createRoomDealer(RoomDealer.java:18)
	at nicelee.bilibili.Main.getRoomDealer(Main.java:383)
	at nicelee.bilibili.Main.main(Main.java:85)
当前没有发现合适的视频录制器： huya
Exception in thread "main" java.lang.NullPointerException
	at nicelee.bilibili.Main.main(Main.java:90)
./run-huya.bat: line 3: pause: command not found

**Comment by maowayne123** [comment]
系统ubuntu 1804

**Comment by nICEnnnnnnnLee** [comment]
+ `xxx.bat`只是Windows系统下供参考的默认运行脚本, linux下可能有点水土不服    
+ 我在CentOS下测试了一番，直接命令行调用   ok
```
java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=huya"
```
+ 如果脚本运行的话，确实会出现这样的问题，这时需要在脚本传递参数最后加一个`&`号，如下：
```
java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=huya&"
```

**Comment by maowayne123** [comment]
牛逼了老哥 给你个星星
