### ISSUE TITLE
ubuntu 虎牙报错

### ISSUE THREAD

**Issue by maowayne123** [nICEnnnnnnnLee/BilibiliLiveRecorder#46]
log:
部分清晰度不支持选择
org.json.JSONException: JSONObject["stream"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:770)
	at nicelee.bilibili.live.impl.RoomDealerHuya.getRoomInfo(RoomDealerHuya.java:74)
	at nicelee.bilibili.Main.main(Main.java:90)
解析失败！！
run-huya.bat: line 3: $'pause\r': command not found

谢谢大佬

**Comment by maowayne123** [comment]
所有房间的都是一样的情况

**Comment by nICEnnnnnnnLee** [comment]
请确认版本是最新版本。
