### ISSUE TITLE
感谢大佬，我在尝试使用抖音录播时发现解析失败

### ISSUE THREAD

**Issue by AIeasy** [nICEnnnnnnnLee/BilibiliLiveRecorder#55]
尝试使用抖音录制时一直显示解析失败请问大佬我是哪里用错了吗？
C:\Users\Sean Hu\Desktop\BilibiliLiveRecord.v2.13.0>java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=false&delete=false&liver=douyin&id=&qn=0&retry=5"
douyin 直播录制 version v2.13.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
J4F9MAC
org.json.JSONException: JSONObject["room"] not found.
        at org.json.JSONObject.get(JSONObject.java:573)
        at org.json.JSONObject.getJSONObject(JSONObject.java:766)
        at nicelee.bilibili.live.impl.RoomDealerDouyin.getRoomInfo(RoomDealerDouyin.java:70)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:150)
        at nicelee.bilibili.Main.main(Main.java:83)
解析失败！！

C:\Users\Sean Hu\Desktop\BilibiliLiveRecord.v2.13.0>

**Comment by nICEnnnnnnnLee** [comment]
你直接输入分享链接`https://v.douyin.com/xxxxxxx`。
或者放到浏览器里面输入，等它重定向以后获取id，抖音的id是这样的一串数字`686550840343580****`

**Comment by AIeasy** [comment]
好的大佬我解决了问题了
