### ISSUE TITLE
bilibili录制报错

### ISSUE THREAD

**Issue by lxcoo** [nICEnnnnnnnLee/BilibiliLiveRecorder#60]
java.lang.NullPointerException
        at nicelee.bilibili.live.RoomDealer.createRoomDealer(RoomDealer.java:18)
        at nicelee.bilibili.Main.getRoomDealer(Main.java:190)
        at nicelee.bilibili.Main.main(Main.java:79)
当前没有发现合适的视频录制器： bili
Exception in thread "main" java.lang.NullPointerException
        at nicelee.bilibili.Main.getRoomInfo(Main.java:150)
        at nicelee.bilibili.Main.main(Main.java:83)
./run-bili.sh: line 3: pause: command not found

**Comment by nICEnnnnnnnLee** [comment]
#35

**Comment by lxcoo** [comment]
> [＃35](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/issues/35)

啊抱歉..发错日志了，是这个

**Comment by nICEnnnnnnnLee** [comment]
+ 哥, 抓log请把`debug=true`打开。。。
+ 我这边也复现了一下，发现阿B的网络请求有一定概率回复是乱码，估计是这个问题。  
    你等一会再试一下...两下...应该能通(不要太频繁)

**Comment by nICEnnnnnnnLee** [comment]
+ 我估摸着是协议HTTP协议的问题  
   毕竟主流浏览器早就`HTTP2`了，但是我这用的还是`HTTP1.1`。这是一个很明显的特征。
+ 不能确定是不是这个原因，总之等有时间再把网络请求这块重写试一试

**Comment by lxcoo** [comment]
> * 哥，抓log请把`debug=true`打开。。。
> * 我这边也复现现了一下，发现阿B的网络请求有一定概率回复是乱码，估计是这个问题。
>   你等一会再试一下...两下...应该能通（不要太浪费）

好嘞（下次一定）
