### ISSUE TITLE
虎牙失效

### ISSUE THREAD

**Issue by maowayne123** [nICEnnnnnnnLee/BilibiliLiveRecorder#61]
错误为

部分清晰度不支持选择
org.json.JSONException: JSONObject["stream"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:770)
        at nicelee.bilibili.live.impl.RoomDealerHuya.getRoomInfo(RoomDealerHuya.java:74)
        at nicelee.bilibili.Main.main(Main.java:90)
解析失败！！

**Comment by nICEnnnnnnnLee** [comment]
我感到很沮丧。
+ 这个报错看行数不是最新版本的。
+ 我试了一下，能够录制虎牙直播间。我无法复现问题。
+ 这个log不够全，我不知道具体的直播间。
+ 我不知道在你录制失败以后，有没有尝试过录制虎牙其它直播间，这是不是一个共性问题。
