### ISSUE TITLE
抖音无法录制

### ISSUE THREAD

**Issue by obscureExplorer** [nICEnnnnnnnLee/BilibiliLiveRecorder#67]
输入https://live.douyin.com/xxx、 xxx、https://v.douyin.com/xxx/ ，均无法录制，报了
`
java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:536)
        at nicelee.bilibili.live.impl.RoomDealerDouyin4User.getRoomInfo(RoomDealerDouyin4User.java:87)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:152)
        at nicelee.bilibili.Main.main(Main.java:85)
解析失败！！
`
的错

**Comment by ZhangiFeng** [comment]
可以使用客户端获取cookie进行录制，实测有效
