### ISSUE TITLE
斗鱼报错

### ISSUE THREAD

**Issue by Superbia000** [nICEnnnnnnnLee/BilibiliLiveRecorder#69]
环境：JDK 1.8.0_202, Win10 20H2

java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=true&check=true&delete=true&liver=douyu&id=4624967&qn=-1&retry=5&stopAfterOffline=false&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=0.25"

douyu 直播录制 version v2.16.0
发现cookie配置
RoomDealerDouyu-getLiveObj/157 : v=220120211224&did=62998e27e2606cdd79b2a1ae00061501&tt=1640357765&sign=e6af9d5f1626c7e62b3cc895287baaf2
RoomDealerDouyu-getLiveObj/160 : {"error":-15,"msg":"非法请求","data":""}
org.json.JSONException: JSONObject["data"] is not a JSONObject.
        at org.json.JSONObject.getJSONObject(JSONObject.java:770)
        at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:110)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:152)
        at nicelee.bilibili.Main.main(Main.java:85)
解析失败！！

**Comment by Superbia000** [comment]
弃坑了吗
