### ISSUE TITLE
斗鱼未开播的情况下报错

### ISSUE THREAD

**Issue by wcccWT** [nICEnnnnnnnLee/BilibiliLiveRecorder#8]
![image](https://user-images.githubusercontent.com/30851441/66701195-37155680-ed2c-11e9-8d80-9d63a57c3f69.png)
直播间：6042106

douyu 直播录制 version v1.8
RoomDealerDouyu-getLiveObj/155 : v=220120191012&did=2206c59057010dd04573c76400081501&tt=1570879204&sign=dad284eb853158ae4f7fecbf1b6ea05a&cdn=&rate=0&ver=Douyu_219052705&iar=0&ive=1
RoomDealerDouyu-getLiveObj/157 : {"error":-5,"msg":"房间未开播","data":""}
org.json.JSONException: JSONObject["data"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:770)
	at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:108)
	at nicelee.bilibili.Main.main(Main.java:115)
Exception in thread "main" java.lang.NullPointerException
	at nicelee.bilibili.Main.main(Main.java:130)

**Comment by nICEnnnnnnnLee** [comment]
好的👌收到。
另外，cookie是很重要的东西，亲你先登出账户，不要再晒出来(`･ω･´)ฅ
