### ISSUE TITLE
发送GET请求出现异常！

### ISSUE THREAD

**Issue by MYJN** [nICEnnnnnnnLee/BilibiliLiveRecorder#90]
同时执行5个bat,执行24小时+后其中2个出现以下错误,,有设置cookie

java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=kuaishou&id=***&qn=0&retry=5&stopAfterOffline=false&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=5.0&failRetryAfterMinutes=1.0" 
---------------------------
发送GET请求出现异常！java.net.SocketTimeoutException: connect timed out
org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
        at org.json.JSONObject.<init>(JSONObject.java:222)
        at org.json.JSONObject.<init>(JSONObject.java:406)
        at nicelee.bilibili.live.impl.RoomDealerKuaishou.getUserInfoObj(RoomDealerKuaishou.java:128)
        at nicelee.bilibili.live.impl.RoomDealerKuaishou.getRoomInfo(RoomDealerKuaishou.java:38)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:172)
        at nicelee.bilibili.Main.main(Main.java:85)
解析失败！！
--------------------------
发送GET请求出现异常！java.net.SocketTimeoutException: connect timed out
org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
        at org.json.JSONObject.<init>(JSONObject.java:222)
        at org.json.JSONObject.<init>(JSONObject.java:406)
        at nicelee.bilibili.live.impl.RoomDealerKuaishou.getUserInfoObj(RoomDealerKuaishou.java:128)
        at nicelee.bilibili.live.impl.RoomDealerKuaishou.getRoomInfo(RoomDealerKuaishou.java:38)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:172)
        at nicelee.bilibili.threads.ThRecord.run(ThRecord.java:72)
解析失败！！
SignalHandler is running
-------------------------

**Comment by MYJN** [comment]
java.lang.NullPointerException
        at nicelee.bilibili.live.RoomDealer.createRoomDealer(RoomDealer.java:18)
        at nicelee.bilibili.Main.getRoomDealer(Main.java:192)
        at nicelee.bilibili.Main.main(Main.java:81)
当前没有发现合适的视频录制器： ***
Exception in thread "main" java.lang.NullPointerException
        at nicelee.bilibili.Main.getRoomInfo(Main.java:152)
        at nicelee.bilibili.Main.main(Main.java:85)

**Comment by nICEnnnnnnnLee** [comment]
> java.lang.NullPointerException 
at nicelee.bilibili.live.RoomDealer.createRoomDealer(RoomDealer.java:18) 
at nicelee.bilibili.Main.getRoomDealer(Main.java:192) 
at nicelee.bilibili.Main.main(Main.java:81) 
当前没有发现合适的视频录制器： *** 
Exception in thread "main" java.lang.NullPointerException 
at nicelee.bilibili.Main.getRoomInfo(Main.java:152) 
at nicelee.bilibili.Main.main(Main.java:85)

https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/issues/35#issuecomment-608215352_
